trigger: none
pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: build

    jobs:
      - template: build.yml
      - job: checkForVersionUpgrade
        displayName: Check for version upgrade
        pool:
          vmImage: ubuntu-latest
        
        steps:
          - checkout: self
            persistCredentials: true
          - script: |
              PR_ID=$(System.PullRequest.PullRequestId)
              echo "Pull Request ID: $PR_ID"
              echo "https://dev.azure.com/$(System.TeamProject)/$(Build.Repository.Name)/_apis/git/pullrequests/$PR_ID?api-version=7.1"

              # Fetch pull request details, including description, via API
              PR_DETAILS=$(curl -s -u $(System.AccessToken): \
                  -H "Content-Type: application/json" \
                  "https://dev.azure.com/$(System.TeamProject)/$(Build.Repository.Name)/_apis/git/pullrequests/$PR_ID?api-version=7.1")

              # Extract PR description from the API response
              PR_DESCRIPTION=$(echo $PR_DETAILS)

              echo "Pull Request Description: $PR_DESCRIPTION"
            displayName: 'Print PR Description'
          - script: |
              PR_ID=$(System.PullRequest.PullRequestId)
              git commit --amend -m "some #label"
            displayName: amend commit