trigger:
  branches:
    include:
      - main
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: build

    jobs:
      - template: build.yml

  - stage: tag
    dependsOn: build
    jobs:
      - template: tagging.yml

  - stage: getTag
    dependsOn: 
      - build
      - tag
    jobs:
      - job: getTag
        displayName: Get git tag
        pool:
          vmImage: ubuntu-latest
        
        steps:
          - checkout: self
            persistCredentials: true
          - script: |
              git fetch --tags
              LATEST_TAG=$(git describe --tags)
              echo "Latest tag: $LATEST_TAG"
            displayName: 'Tag the repository with a new version'