jobs:
  - job: Build
    displayName: Build project
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    # - script: echo "Parameter version: ${{parameters.buildVersion}}"
    # - script: |
    #     LATEST_TAG=$(git describe --tags --abbrev=0)
    #     echo "Git tag version: $LATEST_TAG"