name: main workflow

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  prerelease-pr-publish:
    needs: build
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/prerelease.yml
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      env: prerelease
    
  prerelease-merge:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/prerelease.yml
    with:
      ref: main
