name: Prelease tagggins and publishing

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      env:
        required: false
        type: string
        
jobs:
  prerelease-tagging:
    runs-on: windows-latest
    environment: ${{ inputs.env }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: modify file to make sure not saved
        run: |
          echo "test" >> version.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Version and commit
        run: |
          npm version prerelease --force
          git push --follow-tags
          npm pack --dry-run